#!/usr/bin/env bash

for x in $(find ../domo* -type f -executable | grep -v "\.git" | grep -vi "domotemplate"); do
  if [ $(basename "$x" | grep -i "domo") ]; then
    bcompare "domotemplate" "$x" &
  fi
done
